name: databases

networks:
  databases:
    name: databases
    driver: bridge

volumes:
  postgresql_data:
    name: postgresql_data
    driver: local

  redis_data:
    name: redis_data
    driver: local

services:
  postgres:
    container_name: PostgreSQL
    image: 'postgres:17-alpine'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - databases
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    container_name: Redis
    image: redis:7.4-alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - databases
    volumes:
      - redis_data:/data
